# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        # this internal class is used by Symfony to represent in-memory users
        Symfony\Component\Security\Core\User: sha256
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    john_admin: { password: 'l8PXGvMMLLFle18ju9PScIXOCElk8/2X/DxAV2whqsE=' }
                    jane_admin: { password: 'l8PXGvMMLLFle18ju9PScIXOCElk8/2X/DxAV2whqsE=' }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout:
                path:   /logout
                target: /
            guard:
                authenticators:
                    - AppBundle\Form\LoginFormAuthenticator
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
